name: Fotovandring.no
favicon: null
layout_spectrum: 0.7291595409624279
typography_spectrum: 0.0058936255518347025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8293207210954279
  lightness: 0.07802836853079498
  saturation: 0.857596495654434
  rhythmicContrast: 0.7587335961870849
purpose: []
